# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dc66d80989d8a77eb73f30fc4ac0706e8a05caaf2e3bb53e4e576e67109aeb110746588f3f9812d34a2d2b0ecab5dfe08862fcaddbe73ba0e38b384ed5836fd

test:
  secret_key_base: 08b58b7378e8ece6226826ba2fa13ac39d356cf844d505cb7a33a57a73902611adddcb21bded8eaa126f05784d7bbb33c1b804234e7b55e895e1c375ce631dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
